#!/usr/bin/perl
require "$ENV{THESIS_PATH}/scripts/pts.inc";

sub y_value($$$) {
	my ($op_count, $type, $file) = @_;
	return value("^vvm\t$type\t$op_count\t", $file, 3) /
	       value("^scalar\t$type\t$op_count\t", $file, 3);
}

$argc = @ARGV;
if($argc == 4) {
	($x, $n, $type, $version_file) = @ARGV;
} else {
	print "To set base directory, set environment variable PTS_BASE\n";
	print "Current PTS_BASE: $BASE\n";
	die "bar_pts <version>\n";
}
for($i = 0; $i < 5; $i++) {
	print $x + ($n * $i);
	print "\t" . y_value($i+1, $type, $version_file) . "\n";
}

