#!/usr/bin/perl
require "$ENV{THESIS_PATH}/scripts/pts.inc";

sub y_value($$$$) {
	my ($op_count, $type, $version, $file) = @_;
	return value("^.*\t$type\t$version\t$op_count\t", $file, 4);
}

sub diff_percent($$) {
	my ($a, $b) = @_;
	return (($b - $a) / $a) * 100;
}

$argc = @ARGV;
if($argc == 1) {
	($type) = @ARGV;
} else {
	print "To set base directory, set environment variable PTS_BASE\n";
	print "Current PTS_BASE: $BASE\n";
	die "table <type>\n";
}
print "\taltivec\tvvm_vp\t%\t\tscalar\tvvm_novp\t%\n";
for($x = 1; $x <= 5; $x++) {
	$altivec = y_value($x, $type, "altivec", "arithmetic_altivec");
	$vvm_vp = y_value($x, $type, "vvm", "arithmetic_vp");
	$diff_vp = diff_percent($altivec, $vvm_vp);
	$scalar = y_value($x, $type, "scalar", "arithmetic_novp");
	$vvm_novp = y_value($x, $type, "vvm", "arithmetic_novp");
	$diff_novp = diff_percent($scalar, $vvm_novp);
	print $x;
	printf "\t%d\t%d\t%3.1f\t", $altivec, $vvm_vp, $diff_vp;
	printf "\t%d\t%d\t%3.1f", $scalar, $vvm_novp, $diff_novp;
	printf "\n";
}

